### test request for server 
GET http://localhost:5000/

### request to see all task
GET http://localhost:3000/api/task

###request to see singular task
GET http://localhost:3000/api/task/4


### posting a new task
POST http://localhost:3000/api/task
content-type: application/json

{
    "name": "Take out trash",
    "priority": "Low"
}

### updating a value in a task
PATCH http://localhost:3000/api/task/2
content-type: application/json

{
    "completed": "true"
}
### deleting a row from the table
DELETE http://localhost:3000/api/task/3